# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/sphinx/conf.py

formats: all

python:
  install:
    # TODO: Remove this requirements file once rtd fully supports dev-dependencies
    - requirements: docs/sphinx/requirements.docs.txt
